### ISSUE TITLE
Fullscreen not working as expected

### ISSUE THREAD

**Issue by Iamproplayer7** [SnosMe/electron-overlay-window#26]
Fullscreen not working, as looking at source it's should work, but event not getting emit and overlay not working in fullscreen mode, borderless windowed everything works good, but at fullscreen nothing on screen,

**Comment by SnosMe** [comment]
- This event is emitted only on Linux. 
- X11 should support `_NET_WM_STATE_FULLSCREEN`.
- I wouldn't be surprised if something breaks inside X11 on your dist, considering my discovery that the order of events is not same #16

**Comment by Iamproplayer7** [comment]
> * This event is emitted only on Linux.
> * X11 should support `_NET_WM_STATE_FULLSCREEN`.
> * I wouldn't be surprised if something breaks inside X11 on your dist, considering my discovery that the order of events is not same [Overlay may appear on the wrong screen #16](https://github.com/SnosMe/electron-overlay-window/issues/16)

Can you try demo example in game called Live for Speed? 
Im using windows 11, multiple monitor. Fullscreen is not working when switched.
It appears for sec and then it disapears forever in fullscreen mode, switching to borderless works again but fullscreen gone forever.

You can download game at https://www.lfs.net/downloads demo version just in main menu.

**Comment by SnosMe** [comment]
> Im using windows 11, Fullscreen is not working

Linux fullscreen is actually the same thing as Borderless Fullsreen Window on Windows.
In both cases desktop compositor allows to show overlay on top of window.
The real Fullscreen mode that is only available on Windows is deprecated by OS, and because it doesnt have compositor, obviously overlay won't show up.

This issue is about implementaion detail on Linux, not the fullscreen!
